/**
 * Install a `mindos` shell command that delegates to the bundled (or dev) CLI.
 * Does not use npm global install — writes ~/.mindos/bin/mindos and optionally
 * appends PATH to ~/.zshrc (etc.).
 */
import { app, dialog, BrowserWindow, Notification } from 'electron';
import path from 'path';
import {
  mkdirSync,
  writeFileSync,
  chmodSync,
  existsSync,
  readFileSync,
  appendFileSync,
} from 'fs';
import { getDefaultBundledMindOsDirectory } from './mindos-runtime-path';
import { resolveCliPath } from './mindos-runtime-layout';
import { getDesktopConfigDir, getDesktopHome } from './desktop-home';
import semver from 'semver';

const SHELL_MARKER = '# MindOS Desktop — CLI (mindos)';

function shimDir(): string {
  return path.join(getDesktopConfigDir(), 'bin');
}

function shimPath(): string {
  return path.join(shimDir(), process.platform === 'win32' ? 'mindos.cmd' : 'mindos');
}

/**
 * Resolve the best CLI entry point: prefer cached runtime (Core Hot Update)
 * over bundled if it has a newer version.
 */
function resolveCliJs(): string | null {
  const bundledRoot = getDefaultBundledMindOsDirectory();
  let bundledCli: string | null = null;
  let bundledVersion: string | null = null;
  if (bundledRoot) {
    const p = resolveCliPath(bundledRoot);
    if (existsSync(p)) {
      bundledCli = p;
      try {
        const pkg = JSON.parse(readFileSync(path.join(bundledRoot, 'package.json'), 'utf-8'));
        bundledVersion = typeof pkg.version === 'string' ? pkg.version : null;
      } catch { /* ignore */ }
    }
  }

  // Check cached runtime (installed by Core Hot Update)
  const cachedRoot = path.join(getDesktopConfigDir(), 'runtime');
  const cachedCli = path.join(cachedRoot, 'bin', 'cli.js');
  if (existsSync(cachedCli)) {
    let cachedVersion: string | null = null;
    try {
      const pkg = JSON.parse(readFileSync(path.join(cachedRoot, 'package.json'), 'utf-8'));
      cachedVersion = typeof pkg.version === 'string' ? pkg.version : null;
    } catch { /* ignore */ }

    // Prefer cached if it has a newer version than bundled
    if (cachedVersion && semver.valid(cachedVersion)) {
      if (!bundledVersion || !semver.valid(bundledVersion) || semver.gt(cachedVersion, bundledVersion)) {
        return cachedCli;
      }
    }
  }

  if (bundledCli) return bundledCli;

  if (!app.isPackaged) {
    const devRoot = path.resolve(app.getAppPath(), '..');
    const dev = resolveCliPath(devRoot);
    return existsSync(dev) ? dev : null;
  }
  return null;
}

/** Safe single-quoted literal for POSIX sh. */
function shellSingleQuote(s: string): string {
  return `'${s.replace(/'/g, `'\"'\"'`)}'`;
}

function writeUnixShim(cliJs: string): void {
  const cliLit = shellSingleQuote(cliJs);
  const script = `#!/bin/sh
# Generated by MindOS Desktop — overwritten on each app launch.

# Guard against deleted working directory (e.g. AI Agent in temp dir)
cd "$HOME" 2>/dev/null || true

CLI=${cliLit}

# If target CLI is missing (e.g. Desktop .app deleted), try npm global fallback
if [ ! -f "$CLI" ]; then
  NPM_ROOT=\$(npm root -g 2>/dev/null)
  NPM_CLI="\${NPM_ROOT}/@geminilight/mindos/bin/cli.js"
  if [ -f "$NPM_CLI" ]; then
    CLI="$NPM_CLI"
  else
    echo "mindos: MindOS Desktop has been removed and no npm global install found." >&2
    echo "" >&2
    echo "  To reinstall CLI:      npm install -g @geminilight/mindos" >&2
    echo "  To clean up residuals:  bash ~/.mindos/uninstall.sh" >&2
    echo "  To reinstall Desktop:   https://mindos.app/download" >&2
    exit 127
  fi
fi

if [ -x "$HOME/.mindos/node/bin/node" ]; then
  exec "$HOME/.mindos/node/bin/node" "$CLI" "$@"
fi
if command -v node >/dev/null 2>&1; then
  exec node "$CLI" "$@"
fi
echo "mindos: Node.js not found. Open MindOS Desktop once (it installs Node under ~/.mindos/node), or install Node 18+." >&2
exit 127
`;
  const out = shimPath();
  mkdirSync(shimDir(), { recursive: true });
  writeFileSync(out, script, 'utf-8');
  try {
    chmodSync(out, 0o755);
  } catch {
    /* ignore */
  }
}

export function escapeCmdSetValue(value: string): string {
  return value
    .replace(/\^/g, '^^')
    .replace(/%/g, '%%')
    .replace(/!/g, '^^!');
}

function writeWindowsShim(cliJs: string): void {
  const nodePrivate = path.join(getDesktopConfigDir(), 'node', 'node.exe');
  const cliEsc = escapeCmdSetValue(cliJs);
  const privEsc = escapeCmdSetValue(nodePrivate);
  const lines = [
    '@echo off',
    'setlocal enabledelayedexpansion',
    // Store CLI path in delayed expansion variable (handles paths with spaces, &, etc.)
    `set "CLI=${cliEsc}"`,
    'if not exist "!CLI!" (',
    '  for /f "delims=" %%i in (\'npm root -g 2^>nul\') do set "NPM_CLI=%%i\\@geminilight\\mindos\\bin\\cli.js"',
    '  if exist "!NPM_CLI!" ( set "CLI=!NPM_CLI!" ) else (',
    '    echo mindos: MindOS Desktop has been removed. Reinstall: npm install -g @geminilight/mindos >&2',
    '    echo To clean up residuals: "%USERPROFILE%\\.mindos\\uninstall.bat" >&2',
    '    exit /b 127',
    '  )',
    ')',
    // Use delayed expansion consistently for node path too
    `set "NODE_PRIV=${privEsc}"`,
    'if exist "!NODE_PRIV!" (',
    '  "!NODE_PRIV!" "!CLI!" %*',
    '  exit /b !ERRORLEVEL!',
    ')',
    'where node >nul 2>&1 || (echo mindos: Node.js not found. Open MindOS Desktop or install Node 18+. >&2 & exit /b 127)',
    'node "!CLI!" %*',
  ];
  mkdirSync(shimDir(), { recursive: true });
  writeFileSync(shimPath(), lines.join('\r\n'), 'utf-8');
}

/**
 * Append ~/.mindos/bin to user PATH on Windows via PowerShell registry API.
 * Uses single-quoted strings to avoid variable expansion issues.
 * Returns true if PATH was modified.
 */
function appendMindosBinToWindowsPath(): boolean {
  const binDir = shimDir();
  try {
    const { execFileSync } = require('child_process');
    const psOpts = { encoding: 'utf-8' as const, timeout: 5000, stdio: ['pipe', 'pipe', 'pipe'] as const };

    // Read current user PATH via PowerShell (execFileSync avoids shell quoting issues)
    let currentPath = '';
    try {
      currentPath = execFileSync('powershell.exe', [
        '-NoProfile', '-Command',
        '[Environment]::GetEnvironmentVariable("Path", "User")',
      ], psOpts).trim();
    } catch { /* empty PATH is fine */ }

    // Check if already present (idempotent)
    const entries = currentPath.split(';').map((s: string) => s.trim().toLowerCase());
    if (entries.includes(binDir.toLowerCase())) return false;

    // Prepend our bin dir — use single-quoted PowerShell string to avoid expansion
    const newPath = `${binDir};${currentPath}`;
    // Escape single quotes for PowerShell single-quoted strings: ' → ''
    const escaped = newPath.replace(/'/g, "''");
    execFileSync('powershell.exe', [
      '-NoProfile', '-Command',
      `[Environment]::SetEnvironmentVariable('Path', '${escaped}', 'User')`,
    ], psOpts);
    console.info(`[MindOS] Added ${binDir} to Windows user PATH`);
    return true;
  } catch (err) {
    console.warn('[MindOS] Could not update Windows PATH:', err instanceof Error ? err.message : err);
    return false;
  }
}

/**
 * Append ~/.mindos/bin to PATH in ALL relevant shell rc files (idempotent per file).
 *
 * AI Agents (Claude Code, Cursor, etc.) run commands via non-interactive shells:
 * - Non-interactive zsh reads ~/.zshenv (NOT ~/.zshrc)
 * - Non-interactive bash reads ~/.bashrc (some systems) or nothing
 * - Fish reads ~/.config/fish/conf.d/*.fish always
 *
 * We must write to ALL relevant files so the PATH is available everywhere.
 * Returns true if we appended to at least one file.
 */
function appendMindosBinToShellRc(): boolean {
  if (process.platform === 'win32') return appendMindosBinToWindowsPath();

  const home = getDesktopHome();
  const block = `\n${SHELL_MARKER}\nexport PATH="$HOME/.mindos/bin:$PATH"\n`;

  // Files to write, in order. "mustCreate" means create the file if it doesn't exist.
  interface RcTarget { name: string; mustCreate: boolean }

  const targets: RcTarget[] =
    process.platform === 'darwin'
      ? [
          { name: '.zshenv',       mustCreate: true },   // non-interactive zsh (AI Agents)
          { name: '.zshrc',        mustCreate: false },   // interactive zsh (user terminal)
          { name: '.bashrc',       mustCreate: true },    // non-interactive bash (AI Agents)
          { name: '.bash_profile', mustCreate: false },   // login bash
        ]
      : [
          { name: '.bashrc',  mustCreate: true },    // bash (interactive + non-interactive)
          { name: '.zshenv',  mustCreate: true },    // non-interactive zsh (AI Agents)
          { name: '.zshrc',   mustCreate: false },   // interactive zsh
          { name: '.profile', mustCreate: false },   // login shell fallback
        ];

  let appended = false;

  for (const { name, mustCreate } of targets) {
    const full = path.join(home, name);
    const fileExists = existsSync(full);

    // Skip non-existent files unless we must create them
    if (!fileExists && !mustCreate) continue;

    // Skip if already has our marker OR CLI marker OR raw PATH line (idempotent)
    if (fileExists) {
      try {
        const content = readFileSync(full, 'utf-8');
        if (content.includes(SHELL_MARKER) || content.includes('# MindOS CLI')
            || content.includes('.mindos/bin')) continue;
      } catch { continue; }
    }

    try {
      appendFileSync(full, block, 'utf-8');
      appended = true;
    } catch {
      // Best effort — don't fail the whole install for one file
    }
  }

  // Fish shell support: write fish-syntax config if fish config dir exists
  try {
    const fishConfD = path.join(home, '.config', 'fish', 'conf.d');
    if (existsSync(fishConfD)) {
      const fishFile = path.join(fishConfD, 'mindos.fish');
      const fishMarker = '# MindOS Desktop — CLI (mindos)';
      const fishBlock = `${fishMarker}\nif not contains "$HOME/.mindos/bin" $PATH\n  set -gx PATH "$HOME/.mindos/bin" $PATH\nend\n`;
      let needsWrite = !existsSync(fishFile);
      if (!needsWrite) {
        const fc = readFileSync(fishFile, 'utf-8');
        needsWrite = !fc.includes(fishMarker) && !fc.includes('# MindOS CLI') && !fc.includes('.mindos/bin');
      }
      if (needsWrite) {
        writeFileSync(fishFile, fishBlock, 'utf-8');
        appended = true;
      }
    }
  } catch { /* best effort */ }

  return appended;
}

export function buildWindowsUninstallScript(): string {
  return [
    '@echo off',
    'setlocal',
    'echo MindOS Cleanup',
    'echo.',
    'set "MINDOS_DIR=%USERPROFILE%\\.mindos"',
    '',
    'rem 1. Kill running MindOS processes',
    'for %%F in ("%MINDOS_DIR%\\mindos.pid" "%MINDOS_DIR%\\desktop-children.pid" "%MINDOS_DIR%\\ssh-tunnel.pid") do (',
    '  if exist "%%~F" (',
    '    for /f "usebackq delims=" %%P in ("%%~F") do (',
    '      for /f "usebackq delims=" %%C in (`powershell.exe -NoProfile -NonInteractive -Command "$p = Get-CimInstance Win32_Process -Filter \'ProcessId = %%P\' -ErrorAction SilentlyContinue; if ($p) { $p.CommandLine }" 2^>nul`) do (',
    '        echo %%C | findstr /I /C:"\\.mindos\\runtime\\" /C:"mindos-runtime" /C:"@geminilight\\mindos" /C:"\\packages\\web\\.next\\standalone\\server.js" /C:"\\dist\\protocols\\mcp-server\\index.cjs" >nul && taskkill /PID %%P /T /F >nul 2>nul',
    '      )',
    '    )',
    '    del /f /q "%%~F" >nul 2>nul',
    '  )',
    ')',
    '',
    'rem 2. Remove Desktop-managed runtimes and CLI shim. Knowledge base is NOT touched.',
    'for %%D in ("%MINDOS_DIR%\\node" "%MINDOS_DIR%\\runtime" "%MINDOS_DIR%\\runtime-downloading" "%MINDOS_DIR%\\runtime-old") do (',
    '  if exist "%%~D" rmdir /s /q "%%~D"',
    ')',
    'del /f /q "%MINDOS_DIR%\\runtime-download.tar.gz" >nul 2>nul',
    'if exist "%MINDOS_DIR%\\bin\\mindos.cmd" del /f /q "%MINDOS_DIR%\\bin\\mindos.cmd"',
    'if exist "%MINDOS_DIR%\\bin" rmdir "%MINDOS_DIR%\\bin" >nul 2>nul',
    '',
    'rem 3. Remove MindOS bin from the user PATH',
    `powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "function Normalize-MindOSPath([string]$p) { if ([string]::IsNullOrWhiteSpace($p)) { return '' }; $expanded = [Environment]::ExpandEnvironmentVariables($p); try { return ([IO.Path]::GetFullPath($expanded)).TrimEnd('\\').ToLowerInvariant() } catch { return $expanded.TrimEnd('\\').ToLowerInvariant() } }; $bin = Join-Path $env:USERPROFILE '.mindos\\bin'; $binNorm = Normalize-MindOSPath $bin; $path = [Environment]::GetEnvironmentVariable('Path', 'User'); if ($path) { $parts = $path -split ';' | Where-Object { $norm = Normalize-MindOSPath $_; $norm -and $norm -ne $binNorm }; [Environment]::SetEnvironmentVariable('Path', ($parts -join ';'), 'User') }" >nul 2>nul`,
    '',
    'rem 4. Remove Desktop config and state files. Knowledge base is NOT touched.',
    'del /f /q "%MINDOS_DIR%\\config.json" >nul 2>nul',
    'del /f /q "%MINDOS_DIR%\\stdin-watchdog.cjs" >nul 2>nul',
    'del /f /q "%MINDOS_DIR%\\desktop-cli-path-notify-v1" >nul 2>nul',
    'del /f /q "%MINDOS_DIR%\\update-status.json" >nul 2>nul',
    'if exist "%MINDOS_DIR%\\tmp" rmdir /s /q "%MINDOS_DIR%\\tmp"',
    'if exist "%MINDOS_DIR%\\sessions" rmdir /s /q "%MINDOS_DIR%\\sessions"',
    'if exist "%APPDATA%\\MindOS" rmdir /s /q "%APPDATA%\\MindOS"',
    'if exist "%LOCALAPPDATA%\\MindOS" rmdir /s /q "%LOCALAPPDATA%\\MindOS"',
    'if exist "%LOCALAPPDATA%\\com.geminilight.mindos" rmdir /s /q "%LOCALAPPDATA%\\com.geminilight.mindos"',
    '',
    'rem 5. Self-remove',
    'del /f /q "%~f0" >nul 2>nul',
    'if exist "%MINDOS_DIR%" rmdir "%MINDOS_DIR%" >nul 2>nul',
    'echo.',
    'echo Done. Your knowledge base was NOT touched.',
    'echo To also remove it: delete %USERPROFILE%\\MindOS\\mind',
    '',
  ].join('\r\n');
}

export function buildUnixUninstallScript(): string {
  return `#!/bin/sh
# MindOS Cleanup Script
# Generated by MindOS Desktop — cleans up residual files after app deletion.
# Your knowledge base (~/MindOS/mind) is NOT touched.

set -e
echo "MindOS Cleanup"
echo ""

is_mindos_cmd() {
  case "$1" in
    */.mindos/runtime/*|*mindos-runtime*|*node_modules/@geminilight/mindos/*|*@geminilight/mindos/*|*/packages/web/.next/standalone/server.js*|*/dist/protocols/mcp-server/index.cjs*)
      return 0
      ;;
  esac
  return 1
}

is_ssh_cmd() {
  comm="$1"
  case "$(basename "$comm")" in
    ssh|ssh.exe)
      return 0
      ;;
  esac
  return 1
}

terminate_pid() {
  pid="$1"
  label="$2"
  kill "$pid" 2>/dev/null && echo "  Stopped $label process $pid" || true
  i=0
  while [ "$i" -lt 10 ]; do
    if ! kill -0 "$pid" 2>/dev/null; then
      return 0
    fi
    sleep 0.1
    i=$((i + 1))
  done
  kill -KILL "$pid" 2>/dev/null || true
}

# 1. Kill running MindOS processes
for pid_file in "$HOME/.mindos/mindos.pid" "$HOME/.mindos/desktop-children.pid"; do
  if [ -f "$pid_file" ]; then
    while IFS= read -r pid; do
      cmd="$(ps -p "$pid" -o args= 2>/dev/null || true)"
      if is_mindos_cmd "$cmd"; then
        terminate_pid "$pid" "MindOS"
      fi
    done < "$pid_file"
    rm -f "$pid_file"
  fi
done

# 1b. Kill orphaned SSH tunnel if it is still owned by ssh.
pid_file="$HOME/.mindos/ssh-tunnel.pid"
if [ -f "$pid_file" ]; then
  while IFS= read -r pid; do
    comm="$(ps -p "$pid" -o comm= 2>/dev/null || true)"
    if is_ssh_cmd "$comm"; then
      terminate_pid "$pid" "SSH tunnel"
    fi
  done < "$pid_file"
  rm -f "$pid_file"
fi

# 2. Remove Desktop-managed runtimes and caches. Knowledge base is NOT touched.
for managed in "$HOME/.mindos/node" "$HOME/.mindos/runtime" "$HOME/.mindos/runtime-downloading" "$HOME/.mindos/runtime-old"; do
  if [ -e "$managed" ]; then
    echo "  Removing $managed..."
    rm -rf "$managed"
  fi
done
rm -f "$HOME/.mindos/runtime-download.tar.gz"

# 3. Remove CLI shim
rm -f "$HOME/.mindos/bin/mindos"
rmdir "$HOME/.mindos/bin" 2>/dev/null || true

# 4. Clean PATH injection from shell rc files
for rc in "$HOME/.zshenv" "$HOME/.zshrc" "$HOME/.zprofile" "$HOME/.bash_profile" "$HOME/.bashrc" "$HOME/.profile"; do
  if [ -f "$rc" ] && grep -Eq '# MindOS Desktop|# MindOS CLI|export PATH="\$HOME/\.mindos/bin:\$PATH"' "$rc"; then
    # Remove current Desktop marker blocks, legacy CLI marker blocks, and exact raw PATH lines.
    if [ "$(uname)" = "Darwin" ]; then
      sed -i '' -e '/# MindOS Desktop/,+1d' -e '/# MindOS CLI/,+1d' -e '\\#export PATH="$HOME/.mindos/bin:$PATH"#d' "$rc"
    else
      sed -i -e '/# MindOS Desktop/,+1d' -e '/# MindOS CLI/,+1d' -e '\\#export PATH="$HOME/.mindos/bin:$PATH"#d' "$rc"
    fi
    echo "  Cleaned $rc"
  fi
done
# Clean fish config
if [ -f "$HOME/.config/fish/conf.d/mindos.fish" ]; then
  rm -f "$HOME/.config/fish/conf.d/mindos.fish"
  echo "  Cleaned fish config"
fi

# 5. Note MCP client configs that still reference MindOS
for cfg in "$HOME/.claude.json" "$HOME/.cursor/mcp.json" "$HOME/.codeium/windsurf/mcp_config.json"; do
  if [ -f "$cfg" ] && grep -q "mindos" "$cfg"; then
    echo "  Note: $cfg still references MindOS — remove the 'mindos' entry manually."
  fi
done

# 6. Remove config and state files
rm -f "$HOME/.mindos/config.json"
rm -f "$HOME/.mindos/stdin-watchdog.cjs"
rm -f "$HOME/.mindos/desktop-cli-path-notify-v1"
rm -f "$HOME/.mindos/update-status.json"
rm -rf "$HOME/.mindos/tmp"
rm -rf "$HOME/.mindos/sessions"

# 7. Remove Electron app data (macOS)
if [ "$(uname)" = "Darwin" ]; then
  rm -rf "$HOME/Library/Application Support/MindOS"
  rm -rf "$HOME/Library/Caches/com.geminilight.mindos"
  rm -f "$HOME/Library/Preferences/com.geminilight.mindos.plist"
fi

# 8. Self-remove
rm -f "$HOME/.mindos/uninstall.sh"
rmdir "$HOME/.mindos" 2>/dev/null || true

echo ""
echo "Done. Your knowledge base was NOT touched."
echo "To also remove it: rm -rf ~/MindOS/mind"
`;
}

/** Generate ~/.mindos/uninstall.sh/.bat for cleanup after app deletion */
function writeUninstallScript(): void {
  const home = getDesktopHome();
  if (process.platform === 'win32') {
    const scriptPath = path.join(home, '.mindos', 'uninstall.bat');
    if (existsSync(scriptPath)) return;
    try {
      mkdirSync(path.dirname(scriptPath), { recursive: true });
      writeFileSync(scriptPath, buildWindowsUninstallScript(), 'utf-8');
    } catch { /* best effort */ }
    return;
  }

  const script = buildUnixUninstallScript();

  const scriptPath = path.join(home, '.mindos', 'uninstall.sh');
  if (existsSync(scriptPath)) return; // idempotent — only create once
  try {
    mkdirSync(path.dirname(scriptPath), { recursive: true });
    writeFileSync(scriptPath, script, 'utf-8');
    chmodSync(scriptPath, 0o755);
  } catch { /* best effort */ }
}

const NOTIFY_FLAG = 'desktop-cli-path-notify-v1';

function notifyFlagPath(): string {
  return path.join(getDesktopConfigDir(), NOTIFY_FLAG);
}

function showMessageBoxSafe(
  parent: BrowserWindow | null | undefined,
  options: Electron.MessageBoxOptions,
): void {
  const win = parent && !parent.isDestroyed() ? parent : null;
  if (win) void dialog.showMessageBox(win, options);
  else void dialog.showMessageBox(options);
}

/** One-time hint after ~/.mindos/bin is appended to shell rc — banner, not a blocking dialog. */
function notifyPathAppendedOnce(): void {
  if (existsSync(notifyFlagPath())) return;
  try {
    writeFileSync(notifyFlagPath(), new Date().toISOString(), 'utf-8');
  } catch {
    /* still try notification */
  }

  const zh = app.getLocale()?.toLowerCase().startsWith('zh');
  const title = zh ? 'mindos 命令行已就绪' : 'mindos CLI is ready';
  const body = zh
    ? '已写入 ~/.mindos/bin 并加入 PATH。请新开终端后运行 mindos --help'
    : '~/.mindos/bin added to PATH. Open a new terminal, then run mindos --help';

  if (Notification.isSupported()) {
    try {
      new Notification({ title, body }).show();
      return;
    } catch {
      /* fall through */
    }
  }
  console.info(`[MindOS] ${title} — ${body}`);
}

/**
 * Sync shim on disk. Call on each launch so CLI tracks the current .app location.
 * Optionally append PATH once; first PATH change triggers a one-time OS notification (no modal).
 */
export function ensureMindosCliShim(opts?: {
  /** default true on macOS/Linux */
  appendPath?: boolean;
}): { ok: boolean; error?: string; pathAppended?: boolean } {
  const cliJs = resolveCliJs();
  if (!cliJs) {
    const msg =
      'Bundled MindOS CLI not found (mindos-runtime/bin/cli.js). Reinstall the app or run from a built repo.';
    console.error('[MindOS]', msg);
    return { ok: false, error: msg };
  }

  try {
    if (process.platform === 'win32') writeWindowsShim(cliJs);
    else writeUnixShim(cliJs);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error('[MindOS] Failed to write CLI shim:', msg);
    return { ok: false, error: msg };
  }

  const doAppend = opts?.appendPath !== false;
  let appended = false;
  if (doAppend) {
    try {
      appended = appendMindosBinToShellRc();
    } catch (e) {
      console.warn('[MindOS] Could not append PATH to shell rc:', e);
    }
  }

  if (appended) notifyPathAppendedOnce();

  writeUninstallScript();

  console.info('[MindOS] CLI shim:', shimPath(), '→', cliJs);
  return { ok: true, pathAppended: appended };
}

export function buildRefreshCliSuccessDialog(
  platform: NodeJS.Platform,
  zh: boolean,
  pathAppended: boolean,
): Electron.MessageBoxOptions {
  if (platform === 'win32') {
    return {
      type: 'info',
      title: zh ? 'mindos 命令' : 'mindos command',
      message: pathAppended
        ? (zh
            ? `已更新 ${shimPath()}，并已将 ${shimDir()} 加入用户 PATH。请新开终端后运行 mindos --help。`
            : `Updated ${shimPath()} and added ${shimDir()} to your user PATH. Open a new terminal, then run mindos --help.`)
        : (zh
            ? `已更新 ${shimPath()}。如果新终端仍找不到 mindos，请将以下目录加入用户 PATH：`
            : `Updated ${shimPath()}. If a new terminal still cannot find mindos, add this folder to your user PATH:`),
      detail: shimDir(),
    };
  }

  return {
    type: 'info',
    title: zh ? 'mindos 命令' : 'mindos command',
    message: zh
      ? '已更新 ~/.mindos/bin/mindos。若终端仍提示找不到命令，请新开终端窗口，或执行 source ~/.zshrc。'
      : 'Updated ~/.mindos/bin/mindos. Open a new terminal or run source ~/.zshrc if the command is not found.',
    detail: shimPath(),
  };
}

/** Tray / manual: refresh shim + show result (and Windows PATH hint). */
export function refreshMindosCliAndNotify(parent: BrowserWindow | null): void {
  const r = ensureMindosCliShim({ appendPath: true });
  const zh = app.getLocale()?.toLowerCase().startsWith('zh');
  if (r.ok) {
    showMessageBoxSafe(parent, buildRefreshCliSuccessDialog(process.platform, zh, r.pathAppended === true));
    return;
  }
  showMessageBoxSafe(parent, {
    type: 'error',
    title: zh ? 'mindos 安装失败' : 'mindos install failed',
    message: r.error ?? 'Unknown error',
  });
}
